"""kombinacija table

Revision ID: bca34eb70c05
Revises: f6a2730062e0
Create Date: 2019-01-29 22:50:34.893555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca34eb70c05'
down_revision = 'f6a2730062e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kombinacija',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('izlet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['izlet_id'], ['izlet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'izlet', type_='foreignkey')
    op.drop_column('izlet', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('izlet', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'izlet', 'user', ['user_id'], ['id'])
    op.drop_table('kombinacija')
    # ### end Alembic commands ###
