"""izleti table

Revision ID: f6a2730062e0
Revises: 5921b62ea38e
Create Date: 2019-01-29 22:40:22.916070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a2730062e0'
down_revision = '5921b62ea38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('izlet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv_izleta', sa.String(length=140), nullable=True),
    sa.Column('lokacija', sa.String(length=140), nullable=True),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.Column('prijevoz', sa.Text(length=140), nullable=True),
    sa.Column('opis_izleta', sa.Text(length=140), nullable=True),
    sa.Column('cijena', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_izlet_datum'), 'izlet', ['datum'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_izlet_datum'), table_name='izlet')
    op.drop_table('izlet')
    # ### end Alembic commands ###
